escamboapp/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
    get 'admins/index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]

  end


  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {sessions: 'members/sessions', registrations: 'members/registrations'}

  root 'site/home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

escamboapp/app/models/ad.rb
class Ad < ApplicationRecord

  # Constants
  QTT_PER_PAGE = 6

  # RatyRate gem
  ratyrate_rateable 'quality'

  # Callbacks
  before_save :md_to_html

  #Associations
  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comments

  #Validates
  validates :title, :description_md, :description_short, presence: true
  validates :picture, :category, :finish_date, presence: true
  validates :price, numericality: { greater_than: 0 }

  # Scopes
  scope :descending_order, ->(page) { order(created_at: :desc).page(page).per(QTT_PER_PAGE) }
  scope :to_the, ->(member) { where(member: member) }
  scope :by_category, ->(id, page) { where(category: id).page(page).per(QTT_PER_PAGE) }
  scope :search, ->(term, page) { where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(QTT_PER_PAGE) }
  scope :random, ->(quantity) { limit(quantity).order("RANDOM()") }

  #peperclip
  has_attached_file :picture, styles: { large: "800x300#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  # gem money-rails
  monetize :price_cents

  def second
    self[1]
  end

  def third
    self[2]
  end

  private

    def md_to_html
      options = {
          filter_html: true,
          link_attributes: {
          rel: "nofollow",
          target: "_blank"
          }
      }

      extensions = {
          space_after_headers: true,
          autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      self.description = markdown.render(self.description_md)
end

end

escamboapp/app/models/admin.rb
class Admin < ApplicationRecord
  # Constants
  ROLES = {:full_access => 0, :restricted_access => 1}
  
  # Enums
  enum role: ROLES

  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  #def self.with_full_access 
  #  where(role: :full_access)
  #end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

  

escamboapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

escamboapp/app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

escamboapp/app/models/category.rb
class Category < ApplicationRecord
  
  # Gem Friendly Id
  include FriendlyId
  friendly_id :description, use: :slugged
  
  #Associations
  has_many :ads

  #Validations
  validates_presence_of :description 
  
  # Scopes
  scope :order_by_description, -> { order(:description) }

end

escamboapp/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

escamboapp/app/models/member.rb
class Member < ApplicationRecord
  
  # RatyRate gem
  ratyrate_rater
  
  # Associations  
  has_many :ads
  has_one :profile_member
  accepts_nested_attributes_for :profile_member

  #Validates
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def nested_attributes
    if nested_attributes_blank?
      errors.add(:base, "É necessário preencher os campos com Nome")
    end
  end

  def nested_attributes_blank?
    profile_member.first_name.blank? || profile_member.second_name.blank?  
  end

end

escamboapp/app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

escamboapp/app/models/profile_member.rb
class ProfileMember < ApplicationRecord
    belongs_to :member

    def full_name
        "#{self.first_name} #{self.second_name}"
    end
end

escamboapp/app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

escamboapp/app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :store_current_location, :unless => :devise_controller?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  layout :layout_by_resource
  
  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
    else
      "application"
    end
  end

  def user_not_authorized
    flash[:alert] = "Você não está autorizado a executar essa ação."
    redirect_to(request.referrer || root_path)
  end

  private

  def store_current_location
    store_location_for(:member, request.url)
  end

end

escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout "backoffice"

    def pundit_user
        current_admin
    end
end

escamboapp/app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

escamboapp/app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout "site"
end

escamboapp/app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

escamboapp/app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        current_member
    end

    def devise_sign_in?
        params[:controller] == 'members/sessions' ? '' : 'display:none;'
    end

    def devise_sign_up?
        params[:controller] == 'members/registrations' ? '' : 'display:none;'
    end
end

escamboapp/app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

escamboapp/app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>

<% if @admin.errors.any?%>
    <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>

    <ul>
        <% @admin.errors.full_messages.each do |message|%>
            <li><%= message %><\li>
        <% end %>
    </ul>

    </div>
<% end %>

<div class="panel panel-default">
        <div class="panel-heading">
            <%= action %>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="col-lg-6">
                <%= form_for([:backoffice, @admin]) do |f|%>
                    <div class="form-group">
                        <label>Nome</label>
                        <%= f.text_field :name, class:"form-control", placeholder:"Nome do Administrador"%>
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <%= f.text_field :email, class:"form-control", placeholder:"Email do Administrador"%>
                    </div>
                    
                    <% if policy(@admin).edit? %>
                        <div class="form-group">
                            <%= f.label :role %>
                            <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                                <div class="radio">
                                    <%= b.label { b.radio_button + b.text } %>
                                </div>
                            <% end %>
                        </div>
                    <% end %>

                    <div class="form-group">
                        <label>Senha</label>
                        <%= f.password_field :password, class:"form-control", placeholder:"Senha"%>
                    </div>
                    <div class="form-group">
                        <label>Confirmação da Senha</label>
                        <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da Senha"%>
                    </div>
                    <button type="submit" class="btn btn-default">Salvar</button>
                <% end %>
            </div>
        </div>
        <!-- /.panel-body -->
</div>

escamboapp/app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do%>
          <div class="form-group">
            <label for="recipient-text" class="control-label">Destinatário:</label>
            <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly") %>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Assunto:</label>
            <%= text_field_tag(:'subject-text', nil, class: "form-control", required: "required") %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Mensagem:</label>
            <%= text_area_tag(:'message-text', nil, class: "form-control") %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <%= submit_tag 'Enviar mensagem', class:"btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

escamboapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escamboapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

escamboapp/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EscamboApp</title>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'backoffice',  media: 'all' %>
    
    <%= csrf_meta_tags %>

    

</head>

<body>

    <div id="wrapper">
      <%= render partial: "layouts/backoffice_shared/navigation" %>
      
      <!-- Page Content -->
      <div id="page-wrapper">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-lg-12">
                      <%= yield %>
                  </div>
                  <!-- /.col-lg-12 -->
              </div>
              <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
      </div>
      <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'backoffice' %>

    <%= render partial: 'layouts/shared/notifications' %>

</body>

</html>

escamboapp/app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EscamboApp</title>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'backoffice',  media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'backoffice' %>

    <%= csrf_meta_tags %>

    

</head>

<body>
    <%= yield %>
</body>

</html>

escamboapp/app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">BackOffice - EscamboApp</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">

    <li><%= current_admin.email%></li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <%= link_to destroy_admin_session_path, method: :delete do %>
                        <i class="fa fa-sign-out fa-fw"></i>
                        Sair
                    <% end %>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <%= link_to backoffice_path do %>
                        <i class="fa fa-dashboard fa-fw"></i> Dashboard
                    <% end %>
                </li>
                <li>
                    <%= link_to backoffice_categories_path do %>
                        <i class="fa fa-th-list fa-fw"></i> Categorias
                    <% end %>
                </li>
                <li>
                    <%= link_to backoffice_admins_path do %>
                        <i class="fa fa-users fa-fw"></i> Administradores
                    <% end %>
                </li>
                <% if Rails.env.development? %>
                    <li>
                        <%= link_to backoffice_diagrams_path do %>
                            <i class="fa fa-database fa-fw"></i> Diagrama ER
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

escamboapp/app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>EscamboApp</title>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'site', media: 'all' %>
    <%= stylesheet_link_tag    'site/profile', media: 'all' %>
    
    <%= csrf_meta_tags %>

</head>

<body>
  <%= render partial: "layouts/site_shared/navigation" %>
  
  
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <%=  link_to "#{t('profile_menu.dashboard')}", site_profile_dashboard_index_path %>
                </li>
                <li>
                    <%=  link_to "#{t('profile_menu.my_ads')}", site_profile_ads_path %>
                </li>
                <li>
                    <%=  link_to "#{t('profile_menu.new_ad')}", new_site_profile_ad_path %>
                </li>
                <li>
                    <%=  link_to "#{t('profile_menu.my_data')}", edit_site_profile_my_datum_path(current_member.id) %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>
    <%= javascript_include_tag 'site/profile' %>
    <%#= javascript_include_tag 'site/profile/ads' %>

    <%= yield :javascript %>

    <%= render partial: 'layouts/shared/notifications' %>

</body>

</html>

escamboapp/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>EscamboApp</title>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'site', media: 'all' %>
    
     <%= csrf_meta_tags %>

</head>

<body>
  <div id="global-spin" class="loading" style="display:none;" >Loading&#8230;</div>
  <%= render partial: "layouts/site_shared/navigation" %>
  
  <!-- Page Content -->
  <div class="container">
    
    <%= form_tag site_search_path, method: :get do %>
      <div class="card card-block mt-3">
        <div class="card card-block mt-3 mb-3 mx-auto" style="width: 600px;">
          <div class="input-group">
                <%= text_field_tag(:q, params[:q], { class:"form-control", placeholder:"Pesquisar por..."}) %>
            <div class="input-group-append">
                <%= submit_tag("Pesquisar", class:"btn btn-outline-secondary") %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="row">

      <%= render partial: 'layouts/site_shared/sidebar' %>

      <div id="home-detail" class="col-lg-9">
        <% if controller_path == 'site/home' %>
            <%= render partial: 'layouts/site_shared/carousel' %>
        <% end %>
        
        <div class="row">
              <%= yield %>
        </div>
        
      </div>
        
    </div>

  </div>
  <!-- /.container -->

  <%= render partial: "layouts/site_shared/footer" %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'site' %>

  <%= render partial: 'layouts/shared/notifications' %>


</body>

</html>

escamboapp/app/views/layouts/site_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EscamboApp</title>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'site',  media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>

    <%= csrf_meta_tags %>

    

</head>

<body>
    <%= yield %>
</body>

</html>

escamboapp/app/views/layouts/site_shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <%= link_to (image_tag @carousel.first.picture.url(:large)), site_ad_detail_path(@carousel.first), remote: true, data: { push: :partial}, class:"d-block img-fluid" %>
        </div>
        <div class="carousel-item">
            <%= link_to (image_tag @carousel.second.picture.url(:large)), site_ad_detail_path(@carousel.second), remote: true, data: { push: :partial}, class:"d-block img-fluid" %>
        </div>
        <div class="carousel-item">
            <%= link_to (image_tag @carousel.third.picture.url(:large)), site_ad_detail_path(@carousel.third), remote: true, data: { push: :partial}, class:"d-block img-fluid" %>
        </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
        </a>
</div>

escamboapp/app/views/layouts/site_shared/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
<div class="container">
    <p class="m-0 text-center text-white">Copyright EscamboApp &copy; Your Website <%= Date.today.year %> </p>
</div>
<!-- /.container -->
</footer>

escamboapp/app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <%= link_to "EscamboApp", site_home_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav ml-auto">
                <% unless member_signed_in?%>
                    <li>
                        <%= link_to "Login", new_member_session_path, class: "nav-link" %>
                    </li>
                    <li>
                        <%= link_to "Cadastrar-se", new_member_registration_path, class: "nav-link" %>
                    </li>
                <% else %>
                    <li>
                        <%= link_to current_member.email, "#", class: "nav-link" %>
                    </li>
                    <li>
                        <%= link_to "Perfil", site_profile_dashboard_index_path, class: "nav-link" %>
                    </li>
                    <li>
                        <%= link_to "Sair", destroy_member_session_path, method: :delete, class: "nav-link"  %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

escamboapp/app/views/layouts/site_shared/_sidebar.html.erb
<div id="home-sidebar" class="col-lg-3">

    <h1 class="my-4">Categorias</h1>
    <div class="list-group">
        <% @categories.each do |category|%>
            <%= link_to "#{category.description} (#{category.ads_count})", site_category_path(category), class: "list-group-item"%>
        <%end%>
    </div>

</div>