escamboapp/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
    get 'admins/index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]

  end


  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {sessions: 'members/sessions', registrations: 'members/registrations'}

  root 'site/home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

escamboapp/app/controllers/site/ad_detail_controller.rb
class Site::AdDetailController < SiteController
    def show
        @categories = Category.order_by_description
        @ad = Ad.find(params[:id])
    end
end

escamboapp/app/controllers/site/categories_controller.rb
class Site::CategoriesController < SiteController

  def show
    @categories = Category.order_by_description
    @category = Category.friendly.find(params[:id])
    @ads = Ad.by_category(@category, params[:page])
  end
end

escamboapp/app/controllers/site/comments_controller.rb
class Site::CommentsController < ApplicationController
    
    before_action :authenticate_member!
    
    def create
        @comment = Comment.new(comment_params)
        @comment.member = current_member

        if @comment.save
            redirect_to site_ad_detail_path(@comment.ad_id), notice: "Comentário adicionado!"
        else
            redirect_to site_ad_detail_path(@comment.ad_id), notice: "Erro ao adicionar comentário!"
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:body, :ad_id)
    end
end

escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(params[:page])
    @carousel = Ad.random(3)
  end
end

escamboapp/app/controllers/site/profile/ads_controller.rb
class Site::Profile::AdsController < Site::ProfileController
    before_action :set_ad, only: [:edit, :update]
    
    def index
      @ads = Ad.to_the(current_member)
    end

    def edit
      #
    end

    def update
      if @ad.update(params_ad)
        redirect_to site_profile_ads_path, notice: "Anúncio atualizado com sucesso!"
      else
        render :edit
      end
    end

    def new
      @ad = Ad.new
    end

    def create
      @ad = Ad.new(params_ad)
      @ad.member = current_member

      if @ad.save
        redirect_to site_profile_ads_path, notice: "Anúncio cadastrado com sucesso!"
      else
        render :new
      end
    end

    private
      def set_ad
        @ad = Ad.find(params[:id])
      end
      
      def params_ad
        params.require(:ad).permit(:id, :title, :category_id, :price, 
                                    :description, :description_md, :description_short, :picture, :finish_date)
      end
end

escamboapp/app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController
  def index
    #
  end
end

escamboapp/app/controllers/site/profile/my_data_controller.rb
class Site::Profile::MyDataController < Site::ProfileController
    before_action :set_profile_member, only: [:edit, :update]

    def edit
    end

    def update
        if @profile_member.update(params_profile_member)
          redirect_to edit_site_profile_my_datum_path(current_member.id), notice: "Perfil atualizado com sucesso!"
        else
          render :edit
        end
      end

    private

    def set_profile_member
        @profile_member = ProfileMember.find_or_create_by(member_id: current_member.id)
      end

    def params_profile_member
        params.require(:profile_member).permit(:id, :first_name, :second_name, :birthdate)
    end
end

escamboapp/app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
    layout "profile"
end
  

escamboapp/app/controllers/site/search_controller.rb
class Site::SearchController < SiteController

    def ads
        @ads = Ad.search(params[:q], params[:page])
        @categories = Category.all
    end
end

escamboapp/app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout "site"
end

escamboapp/app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

escamboapp/app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

escamboapp/app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

escamboapp/app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/helpers/site/profile/ads_helper.rb
module Site::Profile::AdsHelper
end

escamboapp/app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

escamboapp/app/helpers/site/profile/my_data_helper.rb
module Site::Profile::MyDataHelper
end

escamboapp/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

escamboapp/app/views/site/ad_detail/_comment_modal.html.erb
<%= form_tag site_comments_path do%>
  <div class="modal" id="commentModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Deixe seu comentário</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
              <label>Comentário</label>
              <%= text_area :comment, :body, class:"form-control", rows: 5 %>
              <%= hidden_field :comment, :ad_id, value: @ad.id %>
          </div>
        </div>
        <div class="modal-footer">
          <%= submit_tag "Enviar", class:"btn btn-primary" %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

escamboapp/app/views/site/ad_detail/_comments.html.erb
<% @ad.comments.each do |comment| %>
    <p><%= comment.body %></p>
    <small class="text-muted">Feito por <%= comment.member.email %> há  
                                        <%= time_ago_in_words(comment.created_at) %></small>
    <% if (current_member) && (comment.member.id == current_member.id) %>
        <%= rating_for_user @ad, current_member, 'quality' %>
    <% end %>
    <hr>
<% end %>

escamboapp/app/views/site/ad_detail/_show.html.erb
<div class="card mt-4">
  <%= image_tag @ad.picture.url(:large), class:"card-img-top img-fluid" %>
  <div class="card-body">
    <h3 class="card-title"><%= @ad.title %> </h3>
    <h4> <%= humanized_money_with_symbol @ad.price %> </h4>
    <%= @ad.description.html_safe %>
    </div>
</div>

<div class="card w-100 mt-4">
  <div class="card-body">
    <div class="ratings">
      <p class="pull-right"><%= @ad.rates('quality').count %> <%= t('labels.reviews') %></p>
      <%= rating_for @ad, 'quality' %>    
    </div>
  </div>
</div>

<!-- /.card -->
<div class="card card-outline-secondary w-100 my-4">
  <div class="card-header">
    Product Reviews
  </div>
  <div class="card-body">
    
    <% if member_signed_in? %>
      <div class="text-right">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#commentModal">
          Deixe um comentário
        </button>
      </div>
    <% else %>
      <div class="text-right">
        <%= link_to "Efetue login para comentar", new_member_session_path, class:"btn btn-success" %>
      </div>
    <% end %>

    <hr>

    <%= render partial: 'site/ad_detail/comments' %>

  </div>
</div>
<!-- /.card -->

<%= render partial: 'site/ad_detail/comment_modal' %>

escamboapp/app/views/site/ad_detail/show.html.erb
<%= render partial: 'site/ad_detail/show' %>